In [3]:
import numpy as np

array([[77, 48, 98, 74, 32, 67, 41, 30],
       [55, 71, 50, 63, 60, 51, 92, 89],
       [66, 43, 51, 56, 51, 41, 97, 77],
       [88, 47, 87, 90, 30, 33, 41, 94],
       [43, 76, 57, 54, 45, 72, 45, 59],
       [91, 58, 41, 53, 43, 86, 54, 52],
       [76, 45, 38, 90, 82, 34, 39, 95]])

In [15]:
np.random.seed(55)
a=np.random.randint(30,99,20)


array([56, 69, 59, 91, 85, 67, 63, 84, 65, 76, 91, 42, 54, 61, 81, 30, 85,
       92, 73, 79])

In [17]:
a[-1]

79

In [19]:
a[0]

56

In [21]:
a.ndim

1

In [23]:
a.shape

(20,)

In [49]:
b=np.random.randint(30,99,(8,9))
b

array([[42, 65, 76, 89, 95, 48, 43, 92, 67],
       [33, 67, 79, 49, 48, 52, 59, 94, 38],
       [39, 79, 52, 30, 39, 70, 37, 75, 98],
       [44, 40, 33, 67, 53, 71, 76, 34, 44],
       [57, 63, 35, 85, 52, 48, 85, 82, 85],
       [37, 43, 61, 82, 46, 97, 92, 84, 43],
       [79, 66, 92, 72, 31, 37, 35, 78, 98],
       [45, 38, 38, 44, 87, 54, 32, 85, 52]])

In [51]:
b.ndim

2

In [53]:
b.shape

(8, 9)

In [55]:
b[7]

array([45, 38, 38, 44, 87, 54, 32, 85, 52])

In [57]:
b[7,0]

45

## Syntax for Slicling in Multi Dim Array
### array[row start:row end:row step , col start:col end:col step]

In [67]:
b[2:6]

array([[39, 79, 52, 30, 39, 70, 37, 75, 98],
       [44, 40, 33, 67, 53, 71, 76, 34, 44],
       [57, 63, 35, 85, 52, 48, 85, 82, 85],
       [37, 43, 61, 82, 46, 97, 92, 84, 43]])

In [71]:
b[2:6,1:7]

array([[79, 52, 30, 39, 70, 37],
       [40, 33, 67, 53, 71, 76],
       [63, 35, 85, 52, 48, 85],
       [43, 61, 82, 46, 97, 92]])

In [75]:
b[2:6:2,1:7:2]

array([[79, 30, 70],
       [63, 85, 48]])

In [78]:
b[1:5,1:6]

array([[67, 79, 49, 48, 52],
       [79, 52, 30, 39, 70],
       [40, 33, 67, 53, 71],
       [63, 35, 85, 52, 48]])

### The Pandas Library is used for extract data and Manipulate the data

In [99]:
import pandas as pd

In [118]:
r=[4,7,2,9,7,3,90,50]
r

[4, 7, 2, 9, 7, 3, 90, 50]

In [126]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [137]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [143]:
t.shape

(4, 2)

In [149]:
t.ndim

2

In [124]:
np.array(r)

array([ 4,  7,  2,  9,  7,  3, 90, 50])

In [132]:
pd.Series(r)

0     4
1     7
2     2
3     9
4     7
5     3
6    90
7    50
dtype: int64

In [152]:
pd.Series(t) #Since the t is Two Dim we cannot use the Series method...

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [154]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [168]:
df = pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292])
df

name  sub
289     4    7
290     2    9
291     7    3
292    90   50

In [170]:
df.columns

Index(['name', 'sub'], dtype='object')

In [172]:
df['sub']

289     7
290     9
291     3
292    50
Name: sub, dtype: int32

In [176]:
df['sub'].mean()

17.25

In [178]:
df['sub'].median()

8.0

In [180]:
df['sub'].mode()

0     3
1     7
2     9
3    50
Name: sub, dtype: int32

In [182]:
df['sub'].var()

482.9166666666667

In [186]:
df['sub'].std()

21.975364995072702

In [188]:
df['sub'].min()

3

In [190]:
df['sub'].max()

50